### ISSUE TITLE
Art on mp3 file

### ISSUE THREAD

**Issue by Danny-O-dev** [Bluegrams/Vividl#33]
Sorry if this isn't an issue but i have been searching days for a good mp3 downloader that could also put the album art of the song on the mp3 file. I always used soundflush to get songs from soundcloud and have their album art on it. However it suddenly stopped working and i have no alternatives.

I was hoping maybe you guys know if i can do the same with youtube-dl-gui.
This is how the mp3 files with art looked like.
![afbeelding](https://user-images.githubusercontent.com/58507146/130462126-1dfeb70f-7329-4081-ba99-9c14bc2ecb4a.png)

**Comment by alxnull** [comment]
Hey @Danny-O-dev, in case this is still relevant to you:
Vividl currently doesn't download the album art with an mp3 file. However, I just implemented a change so that album art is downloaded and added if "Convert to MP3" is selected for a download. Seems to work with Soundcloud in a quick check I did. This will be released with the next version.

**Comment by alxnull** [comment]
Released in v.0.6.0.
