### ISSUE TITLE
Suggestion: choose custom download name

### ISSUE THREAD

**Issue by JonnyThree** [Bluegrams/Vividl#49]
Hello i use this great tool almost everyday and i think that it's the best gui for yt-dlp today available, but sometimes i need to give a different name to the output file before downloading it, do you think that it's possible to add the opportunity to choose a custom file name before clicking the download button?

**Comment by alxnull** [comment]
Hey, glad to hear that you like this tool and thanks for the suggestion. I'll try to consider this in an upcoming update.

**Comment by JonnyThree** [comment]
so the new version is out, and custom files names before downloading is not possible. thanks however for fixing downloading stats

**Comment by as-muncher** [comment]
https://twitter.com/i/status/1210978856628191233
https://twitter.com/i/status/1199121778058113026

can't download these because I can't select a new file name for the save....but also the errors show and then disappear.  And vividl says "No error log available."  so I can't see a whole history of my download/save errors, at least for the current session.

**Comment by alxnull** [comment]
This has been implemented and the upcoming release will allow customizing download names. Thanks for your patience :)
