### ISSUE TITLE
Crashes when url is entered

### ISSUE THREAD

**Issue by Tomas683** [Bluegrams/Vividl#81]
Hello I recently installed the msi package and cannot get a video to download before it freezes then crashes. I actually used the exe earlier and it was working before also crashing later, so I don't know whats happening. The dlp and app is updated to the most recent version, along with the two additional microsoft programs.

**Comment by alxnull** [comment]
The latest release, [v.0.7.0](https://github.com/Bluegrams/Vividl/releases/tag/v.0.7.0), should resolve this issue. If this is not the case, please re-open this issue and provide further details.

**Comment by Freepony** [comment]
The same thing is on 0.7. I was testing different formats. After each convertation I was deleting the file myself but then I changed settings from overwrite to rename. After an attempt to add a video link the app crashed. Now it crashes every time when I'm trying to add a link, settings reset or changing back to overwrite won't help.

Here are the logs.

`[2023-03-11 05:14] An unhandled exception caused the application to terminate unexpectedly.
Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'YoutubeDLSharp.Metadata.VideoData' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path '', line 1, position 1.
   в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract)
   в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   в Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   в Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   в Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   в YoutubeDLSharp.YoutubeDL.<>c__DisplayClass38_0.<RunVideoDataFetch>b__0(Object o, DataReceivedEventArgs e)
   в YoutubeDLSharp.YoutubeDLProcess.<>c__DisplayClass24_0.<RunAsync>b__0(Object o, DataReceivedEventArgs e)
   в System.Diagnostics.Process.OutputReadNotifyUser(String data)
   в System.Diagnostics.AsyncStreamReader.FlushMessageQueue()
   в System.Diagnostics.AsyncStreamReader.GetLinesFromStringBuilder()
   в System.Diagnostics.AsyncStreamReader.ReadBuffer(IAsyncResult ar)
   в System.IO.Stream.ReadWriteTask.InvokeAsyncCallback(Object completedTask)
   в System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.IO.Stream.ReadWriteTask.System.Threading.Tasks.ITaskCompletionAction.Invoke(Task completingTask)
   в System.Threading.Tasks.Task.FinishContinuations()
   в System.Threading.Tasks.Task.FinishStageThree()
   в System.Threading.Tasks.Task.FinishStageTwo()
   в System.Threading.Tasks.Task.Finish(Boolean bUserDelegateExecuted)
   в System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   в System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   в System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   в System.Threading.ThreadPoolWorkQueue.Dispatch()
   в System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
`
